name: 每日更新納斯達克IPO資訊與行業估值數據

on:
  schedule:
    - cron: '0 2 * * *'  # 每天UTC時間2:00運行（香港時間10:00）
  workflow_dispatch:  # 允許手動觸發

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 確保我們獲取的是最新的main分支，以便後續pull操作
          ref: 'main'
      
      - name: 設置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 安裝依賴
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests matplotlib seaborn plotly beautifulsoup4 lxml
      
      - name: 更新納斯達克IPO數據
        id: update_ipo_info # 給這個步驟一個id，方便日誌中識別
        run: |
          cd scripts
          python fetch_ipo_data.py
          python generate_charts.py
          python generate_pdf_report.py
      
      - name: 更新行業估值數據
        id: update_valuation_data # 給這個步驟一個id
        run: |
          cd scripts/industry_valuation
          python fetch_industry_data.py
      
      - name: 配置Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: 提交更新的數據
        run: |
          # 拉取遠程更改以避免衝突
          # 我們假設目標分支是 main，如果不是，需要相應修改
          git pull origin main --rebase
          git add website/data/ website/charts/ website/pdf/
          # 檢查是否有變更需要提交
          if ! git diff --staged --quiet; then
            git commit -m "每日更新納斯達克IPO數據與行業估值數據 $(date +'%Y-%m-%d')"
            git push
          else
            echo "沒有變更需要提交"
          fi
      
      - name: 部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages # 部署到gh-pages分支
          folder: website # 要部署的文件夾
          token: ${{ secrets.GITHUB_TOKEN }}

