name: 每日更新納斯達克IPO資訊

on:
  schedule:
    # 每天香港時間上午10:00運行（UTC+8，即UTC 02:00）
    - cron: '0 2 * * *'
  workflow_dispatch:  # 允許手動觸發

jobs:
  update-ipo-info:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v2

      - name: 設置Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 安裝依賴
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas matplotlib reportlab

      - name: 收集IPO資訊並生成報告
        run: |
          python scripts/generate_pdf_report.py

      - name: 儲存每日資訊
        run: |
          # 創建歷史目錄（如果不存在）
          mkdir -p history
          # 獲取當前日期
          DATE=$(date +%Y-%m-%d)
          # 創建日期目錄
          mkdir -p history/$DATE
          mkdir -p history/$DATE/charts
          # 複製今日生成的文件到歷史目錄
          cp -r website/charts/* history/$DATE/charts/
          cp website/pdf/nasdaq_ipo_report_$DATE.pdf history/$DATE/

      - name: 生成月度報表（如果是月初或月末）
        run: |
          python scripts/monthly_report.py

      - name: 部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages  # 部署到的分支
          folder: website   # 要部署的文件夾
          clean: false      # 不清除舊文件，保留歷史記錄

      - name: 提交歷史記錄到倉庫
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add history/
          git add website/monthly/
          git commit -m "更新IPO歷史記錄和月度報表 $(date +%Y-%m-%d)" || echo "沒有變更需要提交"
          git push
